// Comprehensive university course catalog
// Each university maps emailDomain -> array of courses

const universities = [
  {
    name: "Harvard University",
    emailDomain: "harvard.edu",
    courses: [
      // Computer Science
      { name: "Introduction to Computer Science", courseNumber: "CS50", department: "Computer Science" },
      { name: "Introduction to AI with Python", courseNumber: "CS50AI", department: "Computer Science" },
      { name: "Web Programming with Python and JS", courseNumber: "CS50W", department: "Computer Science" },
      { name: "Data Structures and Algorithms", courseNumber: "CS124", department: "Computer Science" },
      { name: "Data Science", courseNumber: "CS109A", department: "Computer Science" },
      { name: "Advanced Data Science", courseNumber: "CS109B", department: "Computer Science" },
      { name: "Systems Programming and Machine Organization", courseNumber: "CS61", department: "Computer Science" },
      { name: "Discrete Mathematics", courseNumber: "CS20", department: "Computer Science" },
      { name: "Abstraction and Design in Computation", courseNumber: "CS51", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS181", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS161", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "CS182", department: "Computer Science" },
      { name: "Computational Linguistics", courseNumber: "CS187", department: "Computer Science" },
      { name: "Programming Languages", courseNumber: "CS153", department: "Computer Science" },
      { name: "Computer Vision", courseNumber: "CS283", department: "Computer Science" },
      // Economics
      { name: "Principles of Economics", courseNumber: "ECON10A", department: "Economics" },
      { name: "Principles of Economics", courseNumber: "ECON10B", department: "Economics" },
      { name: "Intermediate Microeconomics", courseNumber: "ECON1010A", department: "Economics" },
      { name: "Intermediate Macroeconomics", courseNumber: "ECON1010B", department: "Economics" },
      { name: "Statistics", courseNumber: "ECON1123", department: "Economics" },
      { name: "Econometrics", courseNumber: "ECON1126", department: "Economics" },
      { name: "Game Theory", courseNumber: "ECON1052", department: "Economics" },
      { name: "International Trade", courseNumber: "ECON1540", department: "Economics" },
      { name: "Labor Economics", courseNumber: "ECON1395", department: "Economics" },
      // Mathematics
      { name: "Multivariable Calculus", courseNumber: "MATH21A", department: "Mathematics" },
      { name: "Linear Algebra and Differential Equations", courseNumber: "MATH21B", department: "Mathematics" },
      { name: "Introduction to Real Analysis", courseNumber: "MATH25A", department: "Mathematics" },
      { name: "Honors Linear Algebra", courseNumber: "MATH25B", department: "Mathematics" },
      { name: "Abstract Algebra", courseNumber: "MATH122", department: "Mathematics" },
      { name: "Real Analysis", courseNumber: "MATH112", department: "Mathematics" },
      { name: "Topology", courseNumber: "MATH131", department: "Mathematics" },
      { name: "Probability", courseNumber: "MATH154", department: "Mathematics" },
      { name: "Number Theory", courseNumber: "MATH129", department: "Mathematics" },
      { name: "Differential Geometry", courseNumber: "MATH136", department: "Mathematics" },
      // Chemistry
      { name: "Organic Chemistry", courseNumber: "CHEM20", department: "Chemistry" },
      { name: "Organic Chemistry II", courseNumber: "CHEM27", department: "Chemistry" },
      { name: "General Chemistry", courseNumber: "CHEM17", department: "Chemistry" },
      { name: "Physical Chemistry", courseNumber: "CHEM60", department: "Chemistry" },
      { name: "Biochemistry", courseNumber: "CHEM30", department: "Chemistry" },
      { name: "Inorganic Chemistry", courseNumber: "CHEM40", department: "Chemistry" },
      // Biology
      { name: "Molecular Biology", courseNumber: "BIO50", department: "Biology" },
      { name: "Introductory Biology", courseNumber: "LIFESCI1A", department: "Biology" },
      { name: "Genetics and Genomics", courseNumber: "LIFESCI1B", department: "Biology" },
      { name: "Cell Biology", courseNumber: "MCB60", department: "Biology" },
      { name: "Neuroscience", courseNumber: "MCB80", department: "Biology" },
      { name: "Evolutionary Biology", courseNumber: "OEB10", department: "Biology" },
      { name: "Ecology", courseNumber: "OEB51", department: "Biology" },
      // Physics
      { name: "Mechanics and Special Relativity", courseNumber: "PHYS15A", department: "Physics" },
      { name: "Electromagnetism", courseNumber: "PHYS15B", department: "Physics" },
      { name: "Waves and Optics", courseNumber: "PHYS15C", department: "Physics" },
      { name: "Quantum Mechanics", courseNumber: "PHYS143A", department: "Physics" },
      { name: "Statistical Mechanics", courseNumber: "PHYS181", department: "Physics" },
      // History
      { name: "Western Intellectual History", courseNumber: "HIST10A", department: "History" },
      { name: "American History to 1877", courseNumber: "HIST97A", department: "History" },
      { name: "Modern European History", courseNumber: "HIST10B", department: "History" },
      { name: "The World Since 1945", courseNumber: "HIST12", department: "History" },
      // English
      { name: "Introduction to Fiction", courseNumber: "ENGL90FA", department: "English" },
      { name: "Introduction to Poetry", courseNumber: "ENGL90PA", department: "English" },
      { name: "Shakespeare", courseNumber: "ENGL129", department: "English" },
      { name: "American Literature", courseNumber: "ENGL170", department: "English" },
      // Philosophy
      { name: "Introduction to Philosophy", courseNumber: "PHIL1", department: "Philosophy" },
      { name: "Ethics", courseNumber: "PHIL22", department: "Philosophy" },
      { name: "Logic", courseNumber: "PHIL6", department: "Philosophy" },
      { name: "Political Philosophy", courseNumber: "PHIL160", department: "Philosophy" },
      // Psychology
      { name: "Introduction to Psychology", courseNumber: "PSY1", department: "Psychology" },
      { name: "Social Psychology", courseNumber: "PSY15", department: "Psychology" },
      { name: "Abnormal Psychology", courseNumber: "PSY18", department: "Psychology" },
      { name: "Cognitive Neuroscience", courseNumber: "PSY1303", department: "Psychology" },
      // Government
      { name: "American Government", courseNumber: "GOV10", department: "Government" },
      { name: "International Relations", courseNumber: "GOV20", department: "Government" },
      { name: "Political Theory", courseNumber: "GOV30", department: "Government" },
      { name: "Comparative Politics", courseNumber: "GOV40", department: "Government" },
      // Statistics
      { name: "Introduction to Probability", courseNumber: "STAT110", department: "Statistics" },
      { name: "Statistical Inference", courseNumber: "STAT111", department: "Statistics" },
      { name: "Applied Statistics", courseNumber: "STAT139", department: "Statistics" },
    ],
  },
  {
    name: "Massachusetts Institute of Technology",
    emailDomain: "mit.edu",
    courses: [
      // EECS
      { name: "Introduction to EECS via Robotics", courseNumber: "6.01", department: "EECS" },
      { name: "Introduction to Algorithms", courseNumber: "6.006", department: "EECS" },
      { name: "Design and Analysis of Algorithms", courseNumber: "6.046", department: "EECS" },
      { name: "Introduction to Machine Learning", courseNumber: "6.036", department: "EECS" },
      { name: "Computer Systems Engineering", courseNumber: "6.033", department: "EECS" },
      { name: "Artificial Intelligence", courseNumber: "6.034", department: "EECS" },
      { name: "Computer Language Engineering", courseNumber: "6.035", department: "EECS" },
      { name: "Circuits and Electronics", courseNumber: "6.002", department: "EECS" },
      { name: "Signals and Systems", courseNumber: "6.003", department: "EECS" },
      { name: "Software Construction", courseNumber: "6.031", department: "EECS" },
      { name: "Database Systems", courseNumber: "6.830", department: "EECS" },
      { name: "Distributed Systems", courseNumber: "6.824", department: "EECS" },
      { name: "Operating System Engineering", courseNumber: "6.828", department: "EECS" },
      { name: "Computer Network Architecture", courseNumber: "6.829", department: "EECS" },
      { name: "Deep Learning", courseNumber: "6.S191", department: "EECS" },
      // Mathematics
      { name: "Linear Algebra", courseNumber: "18.06", department: "Mathematics" },
      { name: "Differential Equations", courseNumber: "18.03", department: "Mathematics" },
      { name: "Calculus with Theory", courseNumber: "18.014", department: "Mathematics" },
      { name: "Analysis I", courseNumber: "18.100A", department: "Mathematics" },
      { name: "Algebra I", courseNumber: "18.701", department: "Mathematics" },
      { name: "Probability and Random Variables", courseNumber: "18.600", department: "Mathematics" },
      { name: "Combinatorial Analysis", courseNumber: "18.211", department: "Mathematics" },
      { name: "Number Theory", courseNumber: "18.781", department: "Mathematics" },
      { name: "Topology", courseNumber: "18.901", department: "Mathematics" },
      // Physics
      { name: "Physics I: Classical Mechanics", courseNumber: "8.01", department: "Physics" },
      { name: "Physics II: Electricity and Magnetism", courseNumber: "8.02", department: "Physics" },
      { name: "Physics III: Vibrations and Waves", courseNumber: "8.03", department: "Physics" },
      { name: "Quantum Physics I", courseNumber: "8.04", department: "Physics" },
      { name: "Statistical Physics I", courseNumber: "8.044", department: "Physics" },
      { name: "Relativity", courseNumber: "8.033", department: "Physics" },
      // Chemistry
      { name: "Principles of Chemical Science", courseNumber: "5.111", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "5.12", department: "Chemistry" },
      { name: "Organic Chemistry II", courseNumber: "5.13", department: "Chemistry" },
      { name: "Thermodynamics and Kinetics", courseNumber: "5.60", department: "Chemistry" },
      { name: "Biochemistry", courseNumber: "5.07", department: "Chemistry" },
      // Biology
      { name: "Introductory Biology", courseNumber: "7.01x", department: "Biology" },
      { name: "Genetics", courseNumber: "7.03", department: "Biology" },
      { name: "Molecular Biology", courseNumber: "7.28", department: "Biology" },
      { name: "Cell Biology", courseNumber: "7.06", department: "Biology" },
      { name: "Neuroscience", courseNumber: "9.01", department: "Biology" },
      // Economics
      { name: "Principles of Microeconomics", courseNumber: "14.01", department: "Economics" },
      { name: "Principles of Macroeconomics", courseNumber: "14.02", department: "Economics" },
      { name: "Intermediate Microeconomic Theory", courseNumber: "14.04", department: "Economics" },
      { name: "Game Theory", courseNumber: "14.12", department: "Economics" },
      { name: "Econometrics", courseNumber: "14.32", department: "Economics" },
      // Mechanical Engineering
      { name: "Mechanics and Materials I", courseNumber: "2.001", department: "Mechanical Engineering" },
      { name: "Dynamics and Control I", courseNumber: "2.003", department: "Mechanical Engineering" },
      { name: "Thermal-Fluids Engineering", courseNumber: "2.005", department: "Mechanical Engineering" },
      { name: "Design and Manufacturing I", courseNumber: "2.007", department: "Mechanical Engineering" },
      // Management / Sloan
      { name: "Financial Accounting", courseNumber: "15.501", department: "Management" },
      { name: "Managerial Finance", courseNumber: "15.414", department: "Management" },
      { name: "Marketing Management", courseNumber: "15.810", department: "Management" },
      { name: "Organizational Processes", courseNumber: "15.311", department: "Management" },
      // Humanities
      { name: "Introduction to Philosophy", courseNumber: "24.00", department: "Philosophy" },
      { name: "Ethics", courseNumber: "24.02", department: "Philosophy" },
      { name: "Introduction to Linguistics", courseNumber: "24.900", department: "Linguistics" },
      { name: "Science Writing", courseNumber: "21W.777", department: "Writing" },
    ],
  },
  {
    name: "Stanford University",
    emailDomain: "stanford.edu",
    courses: [
      // Computer Science
      { name: "Programming Methodology", courseNumber: "CS106A", department: "Computer Science" },
      { name: "Programming Abstractions", courseNumber: "CS106B", department: "Computer Science" },
      { name: "Computer Organization and Systems", courseNumber: "CS107", department: "Computer Science" },
      { name: "Principles of Computer Systems", courseNumber: "CS110", department: "Computer Science" },
      { name: "Design and Analysis of Algorithms", courseNumber: "CS161", department: "Computer Science" },
      { name: "Mining Massive Data Sets", courseNumber: "CS246", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS229", department: "Computer Science" },
      { name: "Deep Learning", courseNumber: "CS230", department: "Computer Science" },
      { name: "Natural Language Processing with Deep Learning", courseNumber: "CS224N", department: "Computer Science" },
      { name: "Convolutional Neural Networks for Visual Recognition", courseNumber: "CS231N", department: "Computer Science" },
      { name: "Artificial Intelligence: Principles and Techniques", courseNumber: "CS221", department: "Computer Science" },
      { name: "Introduction to Databases", courseNumber: "CS145", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS140", department: "Computer Science" },
      { name: "Computer Networking", courseNumber: "CS144", department: "Computer Science" },
      { name: "Introduction to Probability for Computer Scientists", courseNumber: "CS109", department: "Computer Science" },
      { name: "Web Applications", courseNumber: "CS142", department: "Computer Science" },
      // Mathematics
      { name: "Calculus", courseNumber: "MATH19", department: "Mathematics" },
      { name: "Calculus for Engineers", courseNumber: "MATH20", department: "Mathematics" },
      { name: "Multivariable Differential Calculus", courseNumber: "MATH51", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH104", department: "Mathematics" },
      { name: "Real Analysis", courseNumber: "MATH115", department: "Mathematics" },
      { name: "Modern Algebra", courseNumber: "MATH120", department: "Mathematics" },
      { name: "Probability", courseNumber: "MATH151", department: "Mathematics" },
      // Physics
      { name: "Mechanics", courseNumber: "PHYS21", department: "Physics" },
      { name: "Electricity and Magnetism", courseNumber: "PHYS22", department: "Physics" },
      { name: "Waves and Optics", courseNumber: "PHYS23", department: "Physics" },
      { name: "Quantum Mechanics", courseNumber: "PHYS130", department: "Physics" },
      // Economics
      { name: "Principles of Economics", courseNumber: "ECON1", department: "Economics" },
      { name: "Intermediate Microeconomics", courseNumber: "ECON50", department: "Economics" },
      { name: "Intermediate Macroeconomics", courseNumber: "ECON51", department: "Economics" },
      { name: "Econometrics", courseNumber: "ECON102A", department: "Economics" },
      { name: "Game Theory", courseNumber: "ECON160", department: "Economics" },
      // Biology
      { name: "Introduction to Biology", courseNumber: "BIO41", department: "Biology" },
      { name: "Biochemistry", courseNumber: "BIO118", department: "Biology" },
      { name: "Genetics", courseNumber: "BIO82", department: "Biology" },
      { name: "Cell Biology", courseNumber: "BIO130", department: "Biology" },
      // Chemistry
      { name: "General Chemistry", courseNumber: "CHEM31A", department: "Chemistry" },
      { name: "General Chemistry Lab", courseNumber: "CHEM33", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM35", department: "Chemistry" },
      { name: "Physical Chemistry", courseNumber: "CHEM171", department: "Chemistry" },
      // Engineering
      { name: "Engineering Fundamentals", courseNumber: "ENGR40", department: "Engineering" },
      { name: "Statics", courseNumber: "ENGR14", department: "Engineering" },
      { name: "Dynamics", courseNumber: "ENGR15", department: "Engineering" },
      // Psychology
      { name: "Introduction to Psychology", courseNumber: "PSYCH1", department: "Psychology" },
      { name: "Social Psychology", courseNumber: "PSYCH70", department: "Psychology" },
      { name: "Cognitive Psychology", courseNumber: "PSYCH45", department: "Psychology" },
      // English
      { name: "Creative Writing", courseNumber: "ENGLISH90", department: "English" },
      { name: "Shakespeare", courseNumber: "ENGLISH101", department: "English" },
      // Philosophy
      { name: "Introduction to Ethics", courseNumber: "PHIL2", department: "Philosophy" },
      { name: "Logic", courseNumber: "PHIL150", department: "Philosophy" },
      // History
      { name: "Western Civilization", courseNumber: "HIST10", department: "History" },
      { name: "American History", courseNumber: "HIST50", department: "History" },
      // Business
      { name: "Financial Accounting", courseNumber: "GSB311", department: "Business" },
      { name: "Microeconomics for Managers", courseNumber: "GSB200", department: "Business" },
    ],
  },
  {
    name: "Boston University",
    emailDomain: "bu.edu",
    courses: [
      // Computer Science
      { name: "Intro to Programming", courseNumber: "CS111", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CS112", department: "Computer Science" },
      { name: "Introduction to Algorithms", courseNumber: "CS330", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS350", department: "Computer Science" },
      { name: "Software Engineering", courseNumber: "CS411", department: "Computer Science" },
      { name: "Computer Networks", courseNumber: "CS455", department: "Computer Science" },
      { name: "Database Systems", courseNumber: "CS460", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS542", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "CS440", department: "Computer Science" },
      { name: "Computer Architecture", courseNumber: "CS320", department: "Computer Science" },
      // Mathematics
      { name: "Calculus I", courseNumber: "MA123", department: "Mathematics" },
      { name: "Calculus II", courseNumber: "MA124", department: "Mathematics" },
      { name: "Multivariate Calculus", courseNumber: "MA225", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MA242", department: "Mathematics" },
      { name: "Differential Equations", courseNumber: "MA226", department: "Mathematics" },
      { name: "Probability", courseNumber: "MA381", department: "Mathematics" },
      { name: "Statistics", courseNumber: "MA382", department: "Mathematics" },
      // Chemistry
      { name: "General Chemistry", courseNumber: "CH101", department: "Chemistry" },
      { name: "General Chemistry II", courseNumber: "CH102", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CH203", department: "Chemistry" },
      { name: "Organic Chemistry II", courseNumber: "CH204", department: "Chemistry" },
      { name: "Physical Chemistry", courseNumber: "CH351", department: "Chemistry" },
      // Economics
      { name: "Macroeconomics", courseNumber: "EC102", department: "Economics" },
      { name: "Microeconomics", courseNumber: "EC101", department: "Economics" },
      { name: "Intermediate Micro", courseNumber: "EC201", department: "Economics" },
      { name: "Intermediate Macro", courseNumber: "EC202", department: "Economics" },
      { name: "Econometrics", courseNumber: "EC303", department: "Economics" },
      // Biology
      { name: "Introductory Biology I", courseNumber: "BI107", department: "Biology" },
      { name: "Introductory Biology II", courseNumber: "BI108", department: "Biology" },
      { name: "Genetics", courseNumber: "BI206", department: "Biology" },
      { name: "Cell Biology", courseNumber: "BI315", department: "Biology" },
      // Physics
      { name: "Physics I", courseNumber: "PY211", department: "Physics" },
      { name: "Physics II", courseNumber: "PY212", department: "Physics" },
      { name: "Modern Physics", courseNumber: "PY313", department: "Physics" },
      // Psychology
      { name: "Introduction to Psychology", courseNumber: "PS101", department: "Psychology" },
      { name: "Statistics for Psychology", courseNumber: "PS232", department: "Psychology" },
      { name: "Abnormal Psychology", courseNumber: "PS241", department: "Psychology" },
      // Business
      { name: "Financial Accounting", courseNumber: "SM131", department: "Business" },
      { name: "Marketing Concepts", courseNumber: "SM323", department: "Business" },
      { name: "Financial Management", courseNumber: "SM221", department: "Business" },
      // English
      { name: "Introduction to Literary Analysis", courseNumber: "EN120", department: "English" },
      { name: "American Literature", courseNumber: "EN360", department: "English" },
      // History
      { name: "Western Civilization", courseNumber: "HI100", department: "History" },
      { name: "US History Since 1877", courseNumber: "HI172", department: "History" },
    ],
  },
  {
    name: "Yale University",
    emailDomain: "yale.edu",
    courses: [
      { name: "Introduction to Computer Science", courseNumber: "CPSC201", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CPSC223", department: "Computer Science" },
      { name: "Algorithms", courseNumber: "CPSC365", department: "Computer Science" },
      { name: "Introduction to Machine Learning", courseNumber: "CPSC477", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CPSC422", department: "Computer Science" },
      { name: "Introduction to Psychology", courseNumber: "PSYC110", department: "Psychology" },
      { name: "Calculus I", courseNumber: "MATH112", department: "Mathematics" },
      { name: "Calculus II", courseNumber: "MATH115", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH222", department: "Mathematics" },
      { name: "Principles of Economics", courseNumber: "ECON110", department: "Economics" },
      { name: "Intermediate Microeconomics", courseNumber: "ECON121", department: "Economics" },
      { name: "Game Theory", courseNumber: "ECON159", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM161", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CHEM220", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "BIOL101", department: "Biology" },
      { name: "Molecular Biology", courseNumber: "MB&B200", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS180", department: "Physics" },
      { name: "Quantum Mechanics", courseNumber: "PHYS344", department: "Physics" },
      { name: "Introduction to Philosophy", courseNumber: "PHIL115", department: "Philosophy" },
      { name: "Ethics and Politics", courseNumber: "PHIL175", department: "Philosophy" },
      { name: "American History to 1865", courseNumber: "HIST116", department: "History" },
      { name: "Shakespeare", courseNumber: "ENGL200", department: "English" },
      { name: "Financial Accounting", courseNumber: "MGT501", department: "Management" },
      { name: "Introduction to Political Science", courseNumber: "PLSC114", department: "Political Science" },
    ],
  },
  {
    name: "Princeton University",
    emailDomain: "princeton.edu",
    courses: [
      { name: "Introduction to Programming", courseNumber: "COS126", department: "Computer Science" },
      { name: "Algorithms and Data Structures", courseNumber: "COS226", department: "Computer Science" },
      { name: "Introduction to Machine Learning", courseNumber: "COS324", department: "Computer Science" },
      { name: "Computer Architecture", courseNumber: "COS375", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "COS318", department: "Computer Science" },
      { name: "Reasoning About Computation", courseNumber: "COS340", department: "Computer Science" },
      { name: "Multivariable Calculus", courseNumber: "MAT201", department: "Mathematics" },
      { name: "Linear Algebra with Applications", courseNumber: "MAT202", department: "Mathematics" },
      { name: "Real Analysis", courseNumber: "MAT215", department: "Mathematics" },
      { name: "Algebra", courseNumber: "MAT217", department: "Mathematics" },
      { name: "General Physics I", courseNumber: "PHY103", department: "Physics" },
      { name: "General Physics II", courseNumber: "PHY104", department: "Physics" },
      { name: "Quantum Mechanics", courseNumber: "PHY208", department: "Physics" },
      { name: "Microeconomics", courseNumber: "ECO100", department: "Economics" },
      { name: "Macroeconomics", courseNumber: "ECO101", department: "Economics" },
      { name: "Econometrics", courseNumber: "ECO202", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHM201", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHM301", department: "Chemistry" },
      { name: "Molecular Biology", courseNumber: "MOL214", department: "Molecular Biology" },
      { name: "Genetics", courseNumber: "MOL342", department: "Molecular Biology" },
      { name: "Introduction to Philosophy", courseNumber: "PHI200", department: "Philosophy" },
      { name: "Ethics", courseNumber: "PHI202", department: "Philosophy" },
      { name: "American History", courseNumber: "HIS270", department: "History" },
      { name: "Introduction to Psychology", courseNumber: "PSY101", department: "Psychology" },
    ],
  },
  {
    name: "Columbia University",
    emailDomain: "columbia.edu",
    courses: [
      { name: "Introduction to Computer Science in Java", courseNumber: "COMS1004", department: "Computer Science" },
      { name: "Data Structures in Java", courseNumber: "COMS3134", department: "Computer Science" },
      { name: "Advanced Programming", courseNumber: "COMS3157", department: "Computer Science" },
      { name: "Analysis of Algorithms", courseNumber: "COMS4231", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "COMS4701", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "COMS4771", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "COMS4118", department: "Computer Science" },
      { name: "NLP", courseNumber: "COMS4705", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH1101", department: "Mathematics" },
      { name: "Calculus III", courseNumber: "MATH1201", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH2010", department: "Mathematics" },
      { name: "Principles of Economics", courseNumber: "ECON1105", department: "Economics" },
      { name: "Intermediate Microeconomics", courseNumber: "ECON3211", department: "Economics" },
      { name: "General Chemistry I", courseNumber: "CHEM1403", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CHEM2443", department: "Chemistry" },
      { name: "Introductory Biology I", courseNumber: "BIOL1500", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS1401", department: "Physics" },
      { name: "University Writing", courseNumber: "ENGL1010", department: "English" },
      { name: "Introduction to Philosophy", courseNumber: "PHIL1001", department: "Philosophy" },
      { name: "Contemporary Civilization", courseNumber: "HUMA1001", department: "Humanities" },
      { name: "Literature Humanities", courseNumber: "HUMA1002", department: "Humanities" },
      { name: "Introduction to Psychology", courseNumber: "PSYC1001", department: "Psychology" },
      { name: "American Government", courseNumber: "POLS1501", department: "Political Science" },
    ],
  },
  {
    name: "University of Pennsylvania",
    emailDomain: "upenn.edu",
    courses: [
      { name: "Introduction to Computer Programming", courseNumber: "CIS110", department: "Computer Science" },
      { name: "Programming Languages and Techniques", courseNumber: "CIS120", department: "Computer Science" },
      { name: "Data Structures and Algorithms", courseNumber: "CIS121", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CIS380", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CIS520", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "CIS521", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH104", department: "Mathematics" },
      { name: "Calculus II", courseNumber: "MATH114", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH312", department: "Mathematics" },
      { name: "Microeconomics", courseNumber: "ECON001", department: "Economics" },
      { name: "Macroeconomics", courseNumber: "ECON002", department: "Economics" },
      { name: "Statistics", courseNumber: "ECON103", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM101", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM241", department: "Chemistry" },
      { name: "Biology 101", courseNumber: "BIOL101", department: "Biology" },
      { name: "Introduction to Psychology", courseNumber: "PSYC001", department: "Psychology" },
      { name: "Financial Accounting", courseNumber: "ACCT101", department: "Business" },
      { name: "Marketing", courseNumber: "MKTG101", department: "Business" },
      { name: "Corporate Finance", courseNumber: "FNCE100", department: "Business" },
      { name: "Management", courseNumber: "MGMT100", department: "Business" },
    ],
  },
  {
    name: "University of California, Berkeley",
    emailDomain: "berkeley.edu",
    courses: [
      { name: "Structure and Interpretation of Computer Programs", courseNumber: "CS61A", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CS61B", department: "Computer Science" },
      { name: "Machine Structures", courseNumber: "CS61C", department: "Computer Science" },
      { name: "Discrete Mathematics and Probability Theory", courseNumber: "CS70", department: "Computer Science" },
      { name: "Efficient Algorithms and Intractable Problems", courseNumber: "CS170", department: "Computer Science" },
      { name: "Operating Systems and System Programming", courseNumber: "CS162", department: "Computer Science" },
      { name: "Introduction to Machine Learning", courseNumber: "CS189", department: "Computer Science" },
      { name: "Introduction to AI", courseNumber: "CS188", department: "Computer Science" },
      { name: "Internet Architecture and Protocols", courseNumber: "CS168", department: "Computer Science" },
      { name: "Introduction to Database Systems", courseNumber: "CS186", department: "Computer Science" },
      { name: "Computer Security", courseNumber: "CS161", department: "Computer Science" },
      { name: "Deep Learning", courseNumber: "CS182", department: "Computer Science" },
      { name: "Calculus", courseNumber: "MATH1A", department: "Mathematics" },
      { name: "Calculus II", courseNumber: "MATH1B", department: "Mathematics" },
      { name: "Multivariable Calculus", courseNumber: "MATH53", department: "Mathematics" },
      { name: "Linear Algebra and Differential Equations", courseNumber: "MATH54", department: "Mathematics" },
      { name: "Real Analysis", courseNumber: "MATH104", department: "Mathematics" },
      { name: "Abstract Algebra", courseNumber: "MATH113", department: "Mathematics" },
      { name: "General Chemistry", courseNumber: "CHEM1A", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM3A", department: "Chemistry" },
      { name: "General Biology", courseNumber: "BIO1A", department: "Biology" },
      { name: "General Physics", courseNumber: "PHYS7A", department: "Physics" },
      { name: "Introduction to Economics", courseNumber: "ECON1", department: "Economics" },
      { name: "Intermediate Microeconomics", courseNumber: "ECON100A", department: "Economics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH1", department: "Psychology" },
      { name: "American Government", courseNumber: "POLSCI1", department: "Political Science" },
      { name: "Introduction to Philosophy", courseNumber: "PHILOS2", department: "Philosophy" },
      { name: "US History", courseNumber: "HIST7A", department: "History" },
    ],
  },
  {
    name: "University of California, Los Angeles",
    emailDomain: "ucla.edu",
    courses: [
      { name: "Introduction to Computer Science I", courseNumber: "CS31", department: "Computer Science" },
      { name: "Introduction to Computer Science II", courseNumber: "CS32", department: "Computer Science" },
      { name: "Introduction to Computer Organization", courseNumber: "CS33", department: "Computer Science" },
      { name: "Software Construction", courseNumber: "CS35L", department: "Computer Science" },
      { name: "Algorithms and Complexity", courseNumber: "CS180", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS111", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS161", department: "Computer Science" },
      { name: "Calculus of Several Variables", courseNumber: "MATH32A", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH33A", department: "Mathematics" },
      { name: "Differential Equations", courseNumber: "MATH33B", department: "Mathematics" },
      { name: "General Chemistry", courseNumber: "CHEM20A", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM30A", department: "Chemistry" },
      { name: "Life Sciences Core I", courseNumber: "LIFESCI7A", department: "Life Sciences" },
      { name: "Physics for Life Sciences", courseNumber: "PHYS5A", department: "Physics" },
      { name: "Microeconomic Theory", courseNumber: "ECON101", department: "Economics" },
      { name: "Macroeconomic Theory", courseNumber: "ECON102", department: "Economics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH10", department: "Psychology" },
      { name: "Introduction to Sociology", courseNumber: "SOCIOL1", department: "Sociology" },
      { name: "American Government", courseNumber: "POLISCI10", department: "Political Science" },
    ],
  },
  {
    name: "University of Michigan",
    emailDomain: "umich.edu",
    courses: [
      { name: "Introduction to Computer Science", courseNumber: "EECS183", department: "EECS" },
      { name: "Data Structures and Algorithms", courseNumber: "EECS281", department: "EECS" },
      { name: "Computer Organization", courseNumber: "EECS370", department: "EECS" },
      { name: "Operating Systems", courseNumber: "EECS482", department: "EECS" },
      { name: "Machine Learning", courseNumber: "EECS445", department: "EECS" },
      { name: "Web Systems", courseNumber: "EECS485", department: "EECS" },
      { name: "Calculus I", courseNumber: "MATH115", department: "Mathematics" },
      { name: "Calculus II", courseNumber: "MATH116", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH214", department: "Mathematics" },
      { name: "Principles of Economics I", courseNumber: "ECON101", department: "Economics" },
      { name: "Intermediate Microeconomics", courseNumber: "ECON401", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM130", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM210", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "BIOLOGY171", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS140", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH111", department: "Psychology" },
      { name: "Financial Accounting", courseNumber: "ACC271", department: "Business" },
      { name: "American Politics", courseNumber: "POLSCI101", department: "Political Science" },
    ],
  },
  {
    name: "Cornell University",
    emailDomain: "cornell.edu",
    courses: [
      { name: "Object-Oriented Programming and Data Structures", courseNumber: "CS2110", department: "Computer Science" },
      { name: "Functional Programming", courseNumber: "CS3110", department: "Computer Science" },
      { name: "Computer System Organization", courseNumber: "CS3410", department: "Computer Science" },
      { name: "Introduction to Analysis of Algorithms", courseNumber: "CS4820", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS4410", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS4780", department: "Computer Science" },
      { name: "Intro to AI", courseNumber: "CS4700", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH1110", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH2210", department: "Mathematics" },
      { name: "Intro to Microeconomics", courseNumber: "ECON1110", department: "Economics" },
      { name: "Intro to Macroeconomics", courseNumber: "ECON1120", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM2070", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM3570", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "BIOG1440", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS1112", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH1101", department: "Psychology" },
      { name: "American Government", courseNumber: "GOVT1111", department: "Government" },
    ],
  },
  {
    name: "Duke University",
    emailDomain: "duke.edu",
    courses: [
      { name: "Introduction to Computer Science", courseNumber: "CS101", department: "Computer Science" },
      { name: "Data Structures and Algorithms", courseNumber: "CS201", department: "Computer Science" },
      { name: "Computer Architecture", courseNumber: "CS250", department: "Computer Science" },
      { name: "Algorithms", courseNumber: "CS330", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS310", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS371", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH111L", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH221", department: "Mathematics" },
      { name: "Microeconomics", courseNumber: "ECON101", department: "Economics" },
      { name: "Macroeconomics", courseNumber: "ECON102", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM101", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM201", department: "Chemistry" },
      { name: "Introductory Biology I", courseNumber: "BIO201L", department: "Biology" },
      { name: "Physics I", courseNumber: "PHYS151L", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSY101", department: "Psychology" },
      { name: "Introduction to Philosophy", courseNumber: "PHIL101", department: "Philosophy" },
    ],
  },
  {
    name: "Northwestern University",
    emailDomain: "northwestern.edu",
    courses: [
      { name: "Fundamentals of Computer Programming I", courseNumber: "CS111", department: "Computer Science" },
      { name: "Fundamentals of Computer Programming II", courseNumber: "CS211", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CS214", department: "Computer Science" },
      { name: "Design and Analysis of Algorithms", courseNumber: "CS336", department: "Computer Science" },
      { name: "Introduction to AI", courseNumber: "CS348", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS349", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH220", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH240", department: "Mathematics" },
      { name: "Introduction to Microeconomics", courseNumber: "ECON201", department: "Economics" },
      { name: "Introduction to Macroeconomics", courseNumber: "ECON202", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM131", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM210", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "BIOL215", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS135", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH110", department: "Psychology" },
    ],
  },
  {
    name: "University of Chicago",
    emailDomain: "uchicago.edu",
    courses: [
      { name: "Introduction to Computer Science I", courseNumber: "CMSC15100", department: "Computer Science" },
      { name: "Introduction to Computer Science II", courseNumber: "CMSC15200", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CMSC15400", department: "Computer Science" },
      { name: "Algorithms", courseNumber: "CMSC27200", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CMSC35300", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH15100", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH20250", department: "Mathematics" },
      { name: "Analysis in Rn", courseNumber: "MATH20300", department: "Mathematics" },
      { name: "Price Theory", courseNumber: "ECON20000", department: "Economics" },
      { name: "Principles of Macroeconomics", courseNumber: "ECON20200", department: "Economics" },
      { name: "Econometrics", courseNumber: "ECON21010", department: "Economics" },
      { name: "General Chemistry I", courseNumber: "CHEM11100", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CHEM22000", department: "Chemistry" },
      { name: "General Physics I", courseNumber: "PHYS13100", department: "Physics" },
      { name: "Introductory Biology", courseNumber: "BIOS10130", department: "Biology" },
      { name: "Introduction to Philosophy", courseNumber: "PHIL21000", department: "Philosophy" },
    ],
  },
  {
    name: "Georgia Institute of Technology",
    emailDomain: "gatech.edu",
    courses: [
      { name: "Introduction to Computing", courseNumber: "CS1301", department: "Computer Science" },
      { name: "Data Structures and Algorithms", courseNumber: "CS1332", department: "Computer Science" },
      { name: "Computer Organization", courseNumber: "CS2110", department: "Computer Science" },
      { name: "Design and Analysis of Algorithms", courseNumber: "CS3510", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS3210", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS4641", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "CS3600", department: "Computer Science" },
      { name: "Computer Networking", courseNumber: "CS3251", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH1551", department: "Mathematics" },
      { name: "Calculus II", courseNumber: "MATH1552", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH1554", department: "Mathematics" },
      { name: "Differential Equations", courseNumber: "MATH2552", department: "Mathematics" },
      { name: "Probability and Statistics", courseNumber: "MATH3215", department: "Mathematics" },
      { name: "General Chemistry", courseNumber: "CHEM1211K", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM2311", department: "Chemistry" },
      { name: "Physics I", courseNumber: "PHYS2211", department: "Physics" },
      { name: "Physics II", courseNumber: "PHYS2212", department: "Physics" },
      { name: "Principles of Microeconomics", courseNumber: "ECON2101", department: "Economics" },
      { name: "Statics", courseNumber: "COE2001", department: "Engineering" },
      { name: "Dynamics", courseNumber: "COE2001", department: "Engineering" },
      { name: "Introduction to Psychology", courseNumber: "PSYC1101", department: "Psychology" },
    ],
  },
  {
    name: "University of Texas at Austin",
    emailDomain: "utexas.edu",
    courses: [
      { name: "Introduction to Programming", courseNumber: "CS312", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CS314", department: "Computer Science" },
      { name: "Algorithms and Complexity", courseNumber: "CS331", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CS439", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "CS343", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS391L", department: "Computer Science" },
      { name: "Computer Architecture", courseNumber: "CS429", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "M408C", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "M340L", department: "Mathematics" },
      { name: "Differential Equations", courseNumber: "M427J", department: "Mathematics" },
      { name: "Intro to Microeconomics", courseNumber: "ECO304K", department: "Economics" },
      { name: "Intro to Macroeconomics", courseNumber: "ECO304L", department: "Economics" },
      { name: "General Chemistry I", courseNumber: "CH301", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CH320M", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "BIO311C", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHY303K", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSY301", department: "Psychology" },
      { name: "US Government", courseNumber: "GOV310L", department: "Government" },
    ],
  },
  {
    name: "University of Illinois Urbana-Champaign",
    emailDomain: "illinois.edu",
    courses: [
      { name: "Introduction to Computer Science", courseNumber: "CS124", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CS225", department: "Computer Science" },
      { name: "Computer Architecture", courseNumber: "CS233", department: "Computer Science" },
      { name: "System Programming", courseNumber: "CS241", department: "Computer Science" },
      { name: "Algorithms", courseNumber: "CS374", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CS446", department: "Computer Science" },
      { name: "Artificial Intelligence", courseNumber: "CS440", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH221", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH257", department: "Mathematics" },
      { name: "Microeconomics", courseNumber: "ECON102", department: "Economics" },
      { name: "Macroeconomics", courseNumber: "ECON103", department: "Economics" },
      { name: "General Chemistry I", courseNumber: "CHEM102", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CHEM232", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "IB150", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS211", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSYC100", department: "Psychology" },
    ],
  },
  {
    name: "Carnegie Mellon University",
    emailDomain: "cmu.edu",
    courses: [
      { name: "Principles of Imperative Computation", courseNumber: "15-122", department: "Computer Science" },
      { name: "Principles of Functional Programming", courseNumber: "15-150", department: "Computer Science" },
      { name: "Introduction to Computer Systems", courseNumber: "15-213", department: "Computer Science" },
      { name: "Algorithm Design and Analysis", courseNumber: "15-451", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "10-301", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "15-410", department: "Computer Science" },
      { name: "Computer Networks", courseNumber: "15-441", department: "Computer Science" },
      { name: "Deep Learning", courseNumber: "11-785", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "21-120", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "21-241", department: "Mathematics" },
      { name: "Probability", courseNumber: "21-325", department: "Mathematics" },
      { name: "Differential Equations", courseNumber: "21-260", department: "Mathematics" },
      { name: "Microeconomics", courseNumber: "73-102", department: "Economics" },
      { name: "Macroeconomics", courseNumber: "73-103", department: "Economics" },
      { name: "Modern Chemistry I", courseNumber: "09-105", department: "Chemistry" },
      { name: "General Physics I", courseNumber: "33-111", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "85-102", department: "Psychology" },
      { name: "Financial Accounting", courseNumber: "70-391", department: "Business" },
    ],
  },
  {
    name: "New York University",
    emailDomain: "nyu.edu",
    courses: [
      { name: "Introduction to Computer Science", courseNumber: "CSCI-UA101", department: "Computer Science" },
      { name: "Data Structures", courseNumber: "CSCI-UA102", department: "Computer Science" },
      { name: "Computer Systems Organization", courseNumber: "CSCI-UA201", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CSCI-UA202", department: "Computer Science" },
      { name: "Algorithms", courseNumber: "CSCI-UA310", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CSCI-UA473", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH-UA121", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH-UA140", department: "Mathematics" },
      { name: "Intro to Microeconomics", courseNumber: "ECON-UA1", department: "Economics" },
      { name: "Intro to Macroeconomics", courseNumber: "ECON-UA2", department: "Economics" },
      { name: "General Chemistry I", courseNumber: "CHEM-UA125", department: "Chemistry" },
      { name: "Organic Chemistry I", courseNumber: "CHEM-UA225", department: "Chemistry" },
      { name: "Principles of Biology I", courseNumber: "BIOL-UA11", department: "Biology" },
      { name: "General Physics I", courseNumber: "PHYS-UA11", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH-UA1", department: "Psychology" },
      { name: "Financial Accounting", courseNumber: "ACCT-UB1", department: "Business" },
    ],
  },
  {
    name: "University of Washington",
    emailDomain: "uw.edu",
    courses: [
      { name: "Computer Programming I", courseNumber: "CSE142", department: "Computer Science" },
      { name: "Computer Programming II", courseNumber: "CSE143", department: "Computer Science" },
      { name: "Data Structures and Parallelism", courseNumber: "CSE332", department: "Computer Science" },
      { name: "Systems Programming", courseNumber: "CSE333", department: "Computer Science" },
      { name: "Operating Systems", courseNumber: "CSE451", department: "Computer Science" },
      { name: "Machine Learning", courseNumber: "CSE446", department: "Computer Science" },
      { name: "Algorithms", courseNumber: "CSE421", department: "Computer Science" },
      { name: "Calculus I", courseNumber: "MATH124", department: "Mathematics" },
      { name: "Linear Algebra", courseNumber: "MATH308", department: "Mathematics" },
      { name: "Introduction to Microeconomics", courseNumber: "ECON200", department: "Economics" },
      { name: "General Chemistry", courseNumber: "CHEM142", department: "Chemistry" },
      { name: "Organic Chemistry", courseNumber: "CHEM237", department: "Chemistry" },
      { name: "Introductory Biology", courseNumber: "BIOL180", department: "Biology" },
      { name: "General Physics", courseNumber: "PHYS121", department: "Physics" },
      { name: "Introduction to Psychology", courseNumber: "PSYCH101", department: "Psychology" },
    ],
  },
];

module.exports = { universities };
